// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3u8Vz4gYTY87ZFAeoDFogAUsn1xJPyVk',
    appId: '1:1068530641761:web:408ceaa3b427c83aceb320',
    messagingSenderId: '1068530641761',
    projectId: 'kaushalyanxt-67143',
    authDomain: 'kaushalyanxt-67143.firebaseapp.com',
    storageBucket: 'kaushalyanxt-67143.firebasestorage.app',
    measurementId: 'G-SNVS4VBDST',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAFcuMJ12ZNLaUEFBu-sR_xT-ZNZ22JKE',
    appId: '1:1068530641761:android:1f2e85ccfa4add05ceb320',
    messagingSenderId: '1068530641761',
    projectId: 'kaushalyanxt-67143',
    storageBucket: 'kaushalyanxt-67143.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCl2a-B1ejx5ZDY_G50ZfzPyow0gTUTEi0',
    appId: '1:1068530641761:ios:b38aa1086816e679ceb320',
    messagingSenderId: '1068530641761',
    projectId: 'kaushalyanxt-67143',
    storageBucket: 'kaushalyanxt-67143.firebasestorage.app',
    iosBundleId: 'com.example.kaushalyanxtRfid',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCl2a-B1ejx5ZDY_G50ZfzPyow0gTUTEi0',
    appId: '1:1068530641761:ios:b38aa1086816e679ceb320',
    messagingSenderId: '1068530641761',
    projectId: 'kaushalyanxt-67143',
    storageBucket: 'kaushalyanxt-67143.firebasestorage.app',
    iosBundleId: 'com.example.kaushalyanxtRfid',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA3u8Vz4gYTY87ZFAeoDFogAUsn1xJPyVk',
    appId: '1:1068530641761:web:d9f04e5616e8304cceb320',
    messagingSenderId: '1068530641761',
    projectId: 'kaushalyanxt-67143',
    authDomain: 'kaushalyanxt-67143.firebaseapp.com',
    storageBucket: 'kaushalyanxt-67143.firebasestorage.app',
    measurementId: 'G-126RYMX9F6',
  );
}
